name: Update public_data daily

on:
  schedule:
    - cron: "0 10 * * *" # 10:00 UTC daily
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install -U pip wheel
          pip install requests pandas python-dateutil tenacity

      - name: Generate data
        run: |
          mkdir -p public_data
          python main.py

      - name: Commit changes (if any)
        run: |
          if [ -n "$(git status --porcelain public_data/)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add public_data/*.json
            git commit -m "chore(data): daily refresh public_data [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
